# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HastenProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HastenProject
    pod 'Kingfisher'
    pod 'Moya'
    pod 'Gloss'

end
